spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    url: jdbc:mariadb://astar-maria.c5dsp2ro13rz.ap-northeast-2.rds.amazonaws.com:3306/astar_admin
    username: astar6
    password: dktmxkzjavjsl*6
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.moca.web.repository/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.moca.web.domain

